<a href="https://colab.research.google.com/github/wlau818/Ocular-Anomaly/blob/main/Ocular_Anomaly_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub
import os
import shutil
import pandas as pd

c:\Users\winni\Documents\Project\ocular_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# 1. Define your local project target paths
PROJECT_DATA_DIR = "data"
LOCAL_CSV_PATH = os.path.join(PROJECT_DATA_DIR, "ODIR-5K.csv")
LOCAL_CSV_PATH_2 = os.path.join(PROJECT_DATA_DIR, "EyePACS.csv")


# 2. Create the 'data' folder inside your project if it doesn't exist
if not os.path.exists(PROJECT_DATA_DIR):
    os.makedirs(PROJECT_DATA_DIR)
    print(f"Created local directory: {PROJECT_DATA_DIR}")

# 3. Only download and copy if the file isn't already in your project
if not os.path.exists(LOCAL_CSV_PATH):
    print("Fetching file from cache...")
    cache_dir = kagglehub.dataset_download("andrewmvd/ocular-disease-recognition-odir5k")
    cache_csv_path = os.path.join(cache_dir, "ODIR-5K.csv")

    # Copy the file to your project folder
    shutil.copy(cache_csv_path, LOCAL_CSV_PATH)
    print(f"Successfully copied ODIR-5K.csv to local path: {LOCAL_CSV_PATH}")
else:
    print(f"File already exists locally at: {LOCAL_CSV_PATH}")

# creating the second dataset file
if not os.path.exists(LOCAL_CSV_PATH_2):
    print("Fetching file from cache...")
    cache_dir = kagglehub.dataset_download("deathtrooper/glaucoma-dataset-eyepacs-airogs-light-v2")

    # -> THE FIX: Added the specific nested folder where Kaggle hid the metadata file <-
    cache_csv_path = os.path.join(cache_dir, "eyepac-light-v2-512-jpg", "EyePACS.csv")

    # Copy the file to your project folder
    shutil.copy(cache_csv_path, LOCAL_CSV_PATH_2)
    print(f"Successfully copied EyePACS.csv to local path: {LOCAL_CSV_PATH_2}")
else:
    print(f"File already exists locally at: {LOCAL_CSV_PATH_2}")

# 4. Clean load using your new local project path
df = pd.read_csv(
    LOCAL_CSV_PATH,
    encoding="utf-8",
    encoding_errors="replace",
    engine="python",
    on_bad_lines="skip"
)

df_2 = pd.read_csv(
    LOCAL_CSV_PATH_2,
    encoding="utf-8",
    encoding_errors="replace",
    engine="python",
    on_bad_lines="skip"
)

print(f"\nLoaded {len(df)} rows from your project folder.")
print(f"\nLoaded {len(df_2)} rows from your project folder.")

File already exists locally at: data\ODIR-5K.csv
File already exists locally at: data\EyePACS-TRAIN.csv

Loaded 6392 rows from your project folder.

Loaded 9540 rows from your project folder.

In [3]:
# Dataset 1
print(df.shape)
df.head(5)

(6392, 19)

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
0,0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus,0,0,0,1,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",0_right.jpg
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
2,2,42,Male,2_left.jpg,2_right.jpg,laser spot，moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",2_right.jpg
3,4,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4_right.jpg
4,5,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",5_right.jpg

In [4]:
df.isna().sum().sum()
(df['ID'].value_counts() == 1).sum()

324

In [5]:
## Checking the second dataset

print(df_2.shape)
print(df_2.head(5))

(9540, 8)
     id                  file_name label  label_binary      folder  \
0  2580  EyePACS-TRAIN-RG-2580.jpg    RG             1  validation
1  2617  EyePACS-TRAIN-RG-2617.jpg    RG             1  validation
2  2794  EyePACS-TRAIN-RG-2794.jpg    RG             1  validation
3  2696  EyePACS-TRAIN-RG-2696.jpg    RG             1  validation
4  2585  EyePACS-TRAIN-RG-2585.jpg    RG             1  validation

  source_dataset relative_file_type                                file_path
0  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/
1  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/
2  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/
3  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/
4  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/

## Checking for duplicate rows in Dataset 1

There are duplicate rows for one person, difference is the filepath and filename, each for right and left eye for a given person.

This leads to duplicated rows when excluding the filepath and filename in the new `df` where we turn each left and right eye into their own row.

In [6]:
df.loc[df['Left-Fundus'] == '1_left.jpg']

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
3195,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_left.jpg

In [7]:
rows = df.loc[df['Left-Fundus'] == '1_left.jpg', 'filepath']

for p in rows:
    print(p)

../input/ocular-disease-recognition-odir5k/ODIR-5K/Training Images/1_right.jpg
../input/ocular-disease-recognition-odir5k/ODIR-5K/Training Images/1_left.jpg

In [8]:
(df['Left-Fundus'].value_counts() == 1).sum()

324

## Filtering for the Glaucoma and Normal rows in Dataset 1

1. Break up each rows to separate between left and right eye (SQL)
2. Filter out the rows specifically for glaucoma and normal
3. Combine the glaucoma and normal dataset into one df

In [9]:
import sqlite3

def split_row_data(df, check_glaucoma = False):

    conn = sqlite3.connect(":memory:")
    df.to_sql("df", conn, index=False, if_exists="replace")

    # Please check, using DISTINCT to get rid of the repetitive rows where the only differences were the filepaths
    query = """
    SELECT DISTINCT
        ID,
        "Patient Age",
        "Patient Sex",
        "Left-Fundus" AS file_name,
        "Left-Diagnostic Keywords" AS label,
        G as label_binary,
        'left' AS eye_side,
        'ODIR-5K' AS source_dataset
    FROM
        df

    UNION ALL

    SELECT DISTINCT
        ID,
        "Patient Age",
        "Patient Sex",
        "Right-Fundus" AS file_name,
        "Right-Diagnostic Keywords" AS label,
        G as label_binary,
        'right' AS eye_side,
        'ODIR-5K' AS source_dataset
    FROM
        df
    ;
    """
    # apply the query to get a df of the split rows
    out = pd.read_sql_query(query, conn)

    # check for glaucoma if true
    if check_glaucoma == True:
        out = out[out["label"].str.contains("glaucoma", na=False)]

    return out

In [10]:
# df_glaucoma = df[df['G'] == 1]
# print(df_glaucoma.shape)
# print(df_glaucoma['G'].unique())

# # df_glaucoma.head()

# (df_glaucoma['ID'].value_counts() == 1).sum()

In [11]:
print(df.shape)

(6392, 19)

In [12]:
df_glaucoma_split = split_row_data(df, check_glaucoma = True)
print(df_glaucoma_split.shape)
print(df_glaucoma_split.head())

print(df_glaucoma_split['label_binary'].unique())

# df_glaucoma_split[df_glaucoma_split["label"].str.contains("glaucoma", na=False)]
# df_glaucoma_split[df_glaucoma_split["label_binary"] == 1]

(316, 8)
      ID  Patient Age Patient Sex     file_name  \
78    95           46        Male   95_left.jpg
129  153           79        Male  153_left.jpg
141  167           71        Male  167_left.jpg
150  178           54        Male  178_left.jpg
212  247           49        Male  247_left.jpg

                                             label  label_binary eye_side  \
78                              suspected glaucoma             1     left
129                                       glaucoma             1     left
141                                       glaucoma             1     left
150  dry age-related macular degeneration，glaucoma             1     left
212  dry age-related macular degeneration，glaucoma             1     left

    source_dataset
78         ODIR-5K
129        ODIR-5K
141        ODIR-5K
150        ODIR-5K
212        ODIR-5K
[1]

In [13]:
# Checking for duplicated
cols = ["file_name", "label", "label_binary"]

print(df_glaucoma_split[cols].duplicated().sum())

# df_glaucoma_split['file_name'].value_counts()
# print(df_glaucoma_split.loc[df_glaucoma_split['file_name'] == '95_right.jpg'])

# 300 dupes before adding distinct keyword

0

In [14]:
# filtering for normal cases
df_normal = df[df['N'] == 1]
print(df_normal.shape)
print(df_normal.head())

df_normal['G'].unique()

(2101, 19)
      ID  Patient Age Patient Sex   Left-Fundus   Right-Fundus  \
1      1           57        Male    1_left.jpg    1_right.jpg
7      8           59        Male    8_left.jpg    8_right.jpg
68    84           51      Female   84_left.jpg   84_right.jpg
163  191           51      Female  191_left.jpg  191_right.jpg
344  394           63        Male  394_left.jpg  394_right.jpg

    Left-Diagnostic Keywords Right-Diagnostic Keywords  N  D  G  C  A  H  M  \
1              normal fundus             normal fundus  1  0  0  0  0  0  0
7              normal fundus             normal fundus  1  0  0  0  0  0  0
68             normal fundus             normal fundus  1  0  0  0  0  0  0
163            normal fundus             normal fundus  1  0  0  0  0  0  0
344            normal fundus             normal fundus  1  0  0  0  0  0  0

     O                                           filepath labels  \
1    0  ../input/ocular-disease-recognition-odir5k/ODI...  ['N']
7    0  ../input/ocular-disease-recognition-odir5k/ODI...  ['N']
68   0  ../input/ocular-disease-recognition-odir5k/ODI...  ['N']
163  0  ../input/ocular-disease-recognition-odir5k/ODI...  ['N']
344  0  ../input/ocular-disease-recognition-odir5k/ODI...  ['N']

                       target       filename
1    [1, 0, 0, 0, 0, 0, 0, 0]    1_right.jpg
7    [1, 0, 0, 0, 0, 0, 0, 0]    8_right.jpg
68   [1, 0, 0, 0, 0, 0, 0, 0]   84_right.jpg
163  [1, 0, 0, 0, 0, 0, 0, 0]  191_right.jpg
344  [1, 0, 0, 0, 0, 0, 0, 0]  394_right.jpg

array([0], dtype=int64)

In [15]:
df_normal_split = split_row_data(df_normal, check_glaucoma = False)
print(df_normal_split.shape)
print(df_normal_split.head())

(2160, 8)
    ID  Patient Age Patient Sex     file_name          label  label_binary  \
0    1           57        Male    1_left.jpg  normal fundus             0
1    8           59        Male    8_left.jpg  normal fundus             0
2   84           51      Female   84_left.jpg  normal fundus             0
3  191           51      Female  191_left.jpg  normal fundus             0
4  394           63        Male  394_left.jpg  normal fundus             0

  eye_side source_dataset
0     left        ODIR-5K
1     left        ODIR-5K
2     left        ODIR-5K
3     left        ODIR-5K
4     left        ODIR-5K

In [16]:

# Do we want to filter out the low image quality?
print(df_normal_split['label'].unique())
print(df_normal_split.loc[df_normal_split['label'] == 'low image quality'])

<StringArray>
[              'normal fundus',     'normal fundus，lens dust',
     'lens dust，normal fundus', 'normal fundus，normal fundus',
           'low image quality']
Length: 5, dtype: str
        ID  Patient Age Patient Sex      file_name              label  \
1048  4290           51        Male  4290_left.jpg  low image quality

      label_binary eye_side source_dataset
1048             0     left        ODIR-5K

In [17]:
cols = ["file_name", "label", "label_binary"]

print(df_normal_split[cols].duplicated().sum())

df_normal_split['file_name'].value_counts()

0

file_name
1_left.jpg        1
8_left.jpg        1
84_left.jpg       1
191_left.jpg      1
394_left.jpg      1
                 ..
3263_right.jpg    1
3292_right.jpg    1
3325_right.jpg    1
3369_right.jpg    1
3398_right.jpg    1
Name: count, Length: 2160, dtype: int64

In [18]:
# binary labels using the glaucoma column, called label_binary
    # 0 - normal
    # 1 - glaucoma

filtered_df = pd.concat([df_normal_split, df_glaucoma_split])

print(filtered_df.shape)

(2476, 8)

## Combining the two datasets

We want to keep the columns:
- image/file name
- label (binary 0/1)
- label (string description)

In [19]:
print(filtered_df.head(2))
print(df_2.head(2))

   ID  Patient Age Patient Sex   file_name          label  label_binary  \
0   1           57        Male  1_left.jpg  normal fundus             0
1   8           59        Male  8_left.jpg  normal fundus             0

  eye_side source_dataset
0     left        ODIR-5K
1     left        ODIR-5K
     id                  file_name label  label_binary      folder  \
0  2580  EyePACS-TRAIN-RG-2580.jpg    RG             1  validation
1  2617  EyePACS-TRAIN-RG-2617.jpg    RG             1  validation

  source_dataset relative_file_type                                file_path
0  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/
1  EyePACS-TRAIN                jpg  /eyepac-light-v2-512-jpg/validation/RG/

In [20]:
print(filtered_df.columns)      # want to put left fundus and right fundus onto their own row
print(filtered_df.shape)
print(df_2.columns)
print(df_2.shape)

print('Total expected combined rows: ', filtered_df.shape[0] + df_2.shape[0])

Index(['ID', 'Patient Age', 'Patient Sex', 'file_name', 'label',
       'label_binary', 'eye_side', 'source_dataset'],
      dtype='str')
(2476, 8)
Index(['id', 'file_name', 'label', 'label_binary', 'folder', 'source_dataset',
       'relative_file_type', 'file_path'],
      dtype='str')
(9540, 8)
Total expected combined rows:  12016

In [21]:
# Making sure there are no dupliocate rows
cols = ["file_name", "label", "label_binary", "source_dataset"]

print(filtered_df[cols].duplicated().sum())     # have 2342 DUPLICATE ROWS BEFORE SELECT DISTINCT
print(df_2[cols].duplicated().sum())

0
0

In [22]:
conn = sqlite3.connect(":memory:")
filtered_df.to_sql("filtered_df", conn, index=False, if_exists="replace")
df_2.to_sql("df_2", conn, index=False, if_exists="replace")

query = """
SELECT
    file_name,
    label,
    label_binary,
    source_dataset
FROM
    filtered_df

UNION ALL

SELECT
    file_name,
    label,
    label_binary,
    source_dataset
FROM
    df_2
;
"""
# apply the query to get a df of the split rows
combined_df = pd.read_sql_query(query, conn)

print(combined_df.shape)

(12016, 4)

## Train-test split

Splitting our dataset
* 70 train
* 20 test
* 10 validation

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(combined_df, combined_df['label_binary'], test_size=0.3, random_state=123)

X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size = 0.66, random_state=123)

In [24]:
print('Training shape: ', X_train.shape)
print('Validation shape: ', X_val.shape)
print('Test shape: ', X_test.shape)

print('\n')
print('Label Distribution by Percentage')
print('Training: \n', y_train.value_counts() / y_train.shape[0])
print('Validation: \n', y_val.value_counts() / y_val.shape[0])
print('Test: \n', y_test.value_counts() / y_test.shape[0])

Training shape:  (8411, 4)
Validation shape:  (1225, 4)
Test shape:  (2380, 4)


Label Distribution by Percentage
Training:
 label_binary
0    0.576983
1    0.423017
Name: count, dtype: float64
Validation:
 label_binary
0    0.586939
1    0.413061
Name: count, dtype: float64
Test:
 label_binary
0    0.570588
1    0.429412
Name: count, dtype: float64

In [25]:
X_train.head()

                       file_name label  label_binary source_dataset
9369  EyePACS-TRAIN-NRG-2189.jpg   NRG             0  EyePACS-TRAIN
8516    EyePACS-DEV-NRG-1335.jpg   NRG             0    EyePACS-DEV
4329     EyePACS-TRAIN-RG-52.jpg    RG             1  EyePACS-TRAIN
3564   EyePACS-TRAIN-RG-3067.jpg    RG             1  EyePACS-TRAIN
7513   EyePACS-TRAIN-RG-1669.jpg    RG             1  EyePACS-TRAIN

In [26]:
# Checking dataset distribution
X_train['source_dataset'].value_counts()

source_dataset
EyePACS-TRAIN    4565
EyePACS-DEV      2114
ODIR-5K          1732
Name: count, dtype: int64

In [27]:
import splitfolders

In [29]:
import os
BASE_DIR = "./Images"

def get_source_path(row):

    if "EyePACS" in row["source_dataset"]:
        folder = "EyePACS" 
    else:
        folder = row["source_dataset"]

    return os.path.join(BASE_DIR, folder, row["file_name"])

In [31]:
import shutil

splits = {
    "train": X_train,
    "val": X_val,
    "test": X_test
}

# looking at the splits I just name, iterate through each item/dataset
for split_name, df in splits.items():
    # for each dataset, iterate through the rows
    for _, row in df.iterrows():

        src_path = get_source_path(row)

        label_folder = str(row['label_binary'])

        #    new dir     ./Images   train or val or test    0 or 1
        dst_dir = os.path.join(BASE_DIR, split_name, label_folder)

        os.makedirs(dst_dir, exist_ok = True)

        # grabbing the file name from the dataset
        dst_path = os.path.join(dst_dir, row['file_name'])

        if os.path.exists(src_path):
            shutil.copy2(src_path, dst_path)
        else: 
            print(f'Missing: {src_path}')

In [32]:
print(len(X_train), len(X_val), len(X_test))

8411 1225 2380